### ISSUE TITLE
Micro-Browser-Logo Is Non-Existent on "blog.ubports.com"

### ISSUE THREAD

**Issue by 3rdwiki** [ubports/ubports.com#11]
Looking at the [blog mainpage](https://blog.ubports.com/) ......

I noticed that there was **no browser icon** - [image here](http://imgur.com/BnTEIyE) - that loads to declare the ubports logo.

Seems quite amateurish at present.

**Comment by UniversalSuperBox** [comment]
Closing, incorrect repository. Recreated in the correct one here: https://github.com/ubports/blog.ubports.com/issues/2
