### ISSUE TITLE
Notifications are ineffective on "forums.ubports.com"

### ISSUE THREAD

**Issue by 3rdwiki** [ubports/ubports.com#12]
Hi there,

So everytime I logon to forums.ubports.com/ I see [this notification display](http://imgur.com/2VD6gw6) ,
 the only problem is that it doesn't actually notify me of anything.

It says it has 5 notifications.

But of what (?) I haven't a clue !

**Comment by NeoTheThird** [comment]
I think that should be fixed now. We've been doing some re-skinning on the forums. Could you check if this is still an issue for you?
