### ISSUE TITLE
The forum should use the navigation-bar above its toolbar

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports.com#20]
If you want to return to the homepage from the forums, you have manually edit the URL. Putting the primary navigation from ubports.com above the toolbar on forums.ubports.com would greatly improve accessibility!

**Comment by UniversalSuperBox** [comment]
Looking at NodeBB's options, I don't think there's a way to insert a header above the header without writing a plugin or editing NodeBB in some other way. As much as I'd *love* to do that, I don't think the goal justifies the work.

**Comment by NeoTheThird** [comment]
Alright then, let's close it for now. Thx for looking into it.
