### ISSUE TITLE
Untranslatable website 

### ISSUE THREAD

**Issue by Pharaone** [ubports/ubports.com#25]

**Comment by NeoTheThird** [comment]
I think this is beyond the scope of our project, but i'll address this in the next meeting.

**Comment by ghost** [comment]
I would be happy to help for the translation in French, let me know if you are interested.

**Comment by NeoTheThird** [comment]
We will not translate our main website, since it's too much work for us to maintain...

The Ubuntu Loco teams are encouraged to keep their localized ubuntu touch documentation open.
