### ISSUE TITLE
Wrong link to Patreon

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubports.com#27]
From https://forums.ubports.com/topic/311/mailing-list:

while reading it, i saw the section about Patreon, so at the end of the paragraph i saw "Learn more at patreon.com/ubports", so i was interested to learn what patreon is or do, so i have clicked on the link and a 404 page had opened https://ubports.com/patreon.com/ubports.

**Comment by UniversalSuperBox** [comment]
This has been fixed on our mailing list backend.
