### ISSUE TITLE
"get involved" page links to launchpad

### ISSUE THREAD

**Issue by paulmueller** [ubports/ubports.com#28]
I assume the link under "testing and quality assurance" should link to the wiki article.

https://wiki.ubports.com/wiki/UBports-Bug-Trackers

**Comment by Flohack74** [comment]
Which page is affected by this issue?

**Comment by paulmueller** [comment]
https://ubports.com/page/vo-get-involved

**Comment by Flohack74** [comment]
Can you please check again, should link to Github now ;)

**Comment by paulmueller** [comment]
I think a link to the wiki page (OP) would be better. The GitHub repo links there as well ("make sure you are in the right place"). If you link to the wiki page, chances are higher bugs are opened in the right repo.

**Comment by Flohack74** [comment]
@NeoTheThird what do you think?

**Comment by NeoTheThird** [comment]
It's fixed now. Also, the launchpad trackers now redirect to GitHub.
