### ISSUE TITLE
Youtube Link on event page

### ISSUE THREAD

**Issue by Gabriele69** [ubports/ubports.com#29]
https://ubports.com/event/community-update-24-06-2017-2017-06-24-4/register

Hi guys,
This web page shows the videos of previous QA sessions. The problem is, they can not be seen: "Watch this video on Youtube: Playing on other websites has been disabled by the video owner."

g

**Comment by NeoTheThird** [comment]
Fixed

**Comment by Gabriele69** [comment]
Thank You!
