### ISSUE TITLE
404 for https://ubports.com/img/robot-t.png

### ISSUE THREAD

**Issue by Talkless** [ubports/ubports.com#44]
![ubports_404](https://user-images.githubusercontent.com/292191/27760291-834b84b4-5e4c-11e7-9893-1c705ff967be.png)

**Comment by Flohack74** [comment]
You mean that one?
![grafik](https://user-images.githubusercontent.com/16186470/27805523-7aaac3ac-6035-11e7-8a7f-2529156baed4.png)

**Comment by Talkless** [comment]
It was missing on the bottom too.

It's working now, thanks.
