### ISSUE TITLE
Forum search doesn't seem to be working correctly

### ISSUE THREAD

**Issue by doniks** [ubports/ubports.com#45]
- go to forums.ubports.com
- click on the search icon
- type torrent
=> No matches found

However, there IS at least one obvious hit:
https://forums.ubports.com/topic/359/torrent-app

**Comment by UniversalSuperBox** [comment]
I am not able to confirm this bug. Are you logged in, and what other information can you provide? Browser, OS, anything else?

![image](https://user-images.githubusercontent.com/21966173/27773544-b3e70ad0-5f41-11e7-86a2-e4f2f7f1787e.png)

**Comment by doniks** [comment]
mhm. strange. can't reproduce it anymore either. works fine now.
