### ISSUE TITLE
[Stats] Summarize channels that are the same

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports.com#47]
Only the following channels should be displayed on stats.ubports.com:

- 15.04/devel
- 15.04/rc
- 15.04/stable
- 16.04/devel
- 16.04/rc
- 16.04/stable

**Comment by mymike00** [comment]
Is [stats.ubports.com](https://stats.ubports.com) still online? It isn't apparently...

**Comment by NeoTheThird** [comment]
nope, this can be closed. we can revisit as soon as we have a replacement

**Comment by mymike00** [comment]
Thanks. Also issues https://github.com/ubports/ubuntu-touch/issues/402 and https://github.com/ubports/ubports.com/issues/50 should be closed then :+1:
