### ISSUE TITLE
Redirect blog.ubports.com to ubports.com/blog

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports.com#51]
[The old blog](blog.ubports.com) can still be reached. It should be taken down and redirected to [ubports.com/blog](ubports.ocm/blog).

**Comment by 3DJetengine** [comment]
http://tinyurl.com/6-montholdbug

**Comment by UniversalSuperBox** [comment]
I think that should do it. All good? https://blog.ubports.com

https://github.com/ubports/blog.ubports.com/commit/6a3fa2394e1338e3b629c9181c5b228b9560a23b

**Comment by 3DJetengine** [comment]
well done.

the circle is complete.

**Comment by 3DJetengine** [comment]
you need to claim the bounty now (Dalton Durst or UniversalSuperBox or who-ever you are this week).

**Comment by 3DJetengine** [comment]
would have been better to link to [here](https://ubports.com/blog/latest-news-1) actually.

https://ubports.com/blog/latest-news-1

**Comment by UniversalSuperBox** [comment]
I would agree, but that link doesn't include *all* of the blog content.

**Comment by 3DJetengine** [comment]
@UniversalSuperBox  are there any other re-direction or any other website bounties that require a small bounty ?

**Comment by UniversalSuperBox** [comment]
I don't believe so, but you might find something you like at https://github.com/ubports/ubuntu-touch/issues
