### ISSUE TITLE
Wrong use of the word Patreon

### ISSUE THREAD

**Issue by libermax** [ubports/ubports.com#58]
1. At the bottom of each web page: 

"Donate
Our Sponsors
Donate with Paypal
Donate with Bitcoin
Become a Patreon! "

Patreon use the terms "Become a Patron" not "Become a Patreon" 
So it could be:

1. "Donate
Our Sponsors
Donate with Paypal
Donate with Bitcoin
Donate with Patreon"

Or it could be 

2. "Donate
Our Sponsors
Donate with Paypal
Donate with Bitcoin
Become a Patron !"

Solution 1. is more coherent.

The same wrong use of the word Patreon is spread on many other places and other web sites, docs.ubports.com, ...

**Comment by libermax** [comment]
Has been corrected for several weeks now. 
If someone can close it ...

**Comment by NeoTheThird** [comment]
Thanks for reporting. For future reference, you can also close issues you reported yourself.
