### ISSUE TITLE
FAQ about homebrew is not clear

### ISSUE THREAD

**Issue by doniks** [ubports/ubports.com#61]
This FAQ has multiple issues. It's not written in proper sentences, looks a bit like copy paste mistakes. It should be either fixed or deleted. I wonder how /frequently/ this question has really been asked?!

--

https://ubports.com/community/faq
Is it possible to setup Linuxbrew and install formulae?

Linuxbrew will provide more information.

Features Can install software to a home directory and so does not require sudo Install software not packaged by the native distribution Install up-to-date versions of software when the native distribution is old Use the same package manager to manage both your Mac and GNU/Linux machines

**Comment by prophanetes** [comment]
This issue can probably be closed out?  Sentences seem fine today.  See no reference to homebrew.
