### ISSUE TITLE
Wrong link to Mastodon

### ISSUE THREAD

**Issue by libermax** [ubports/ubports.com#65]
UBports moved to Framapiaf  (https://framapiaf.org/@Ubports) but  website ever still link to mastodon.rocks.

**Comment by libermax** [comment]
Link has been changed but still wrong:   mailto:https://framapiaf.org/@ubports

**Comment by libermax** [comment]
Fixed now

**Comment by neopar** [comment]
On the 'Contact Us' page it is still mailto:https://framapiaf.org/@ubports (in section ' Follow UBports at')
