### ISSUE TITLE
in forum when login the main URL is added before the previous positionURL

### ISSUE THREAD

**Issue by Aury88** [ubports/ubports.com#67]
In the forum if I move in the forum (to eg. https://forums.ubports.com/category/43/ut-for-raspberry-pi) and then I login it adds to my previous location URL the https://forums.ubports.com/ string (in my example  the new url would be https://forums.ubports.com/https://forums.ubports.com/category/43/ut-for-raspberry-pi) resulting in a "Not Found
You seem to have stumbled upon a page that does not exist. Return to the home page." error

Browser: Firefox 70.0.1 (64bit)
Mozzilla Firefox for Ubuntu canonical -1.0
OS: Ubuntu 16.04

**Comment by maciek134** [comment]
Can't reproduce anymore, seems fixed.
