### ISSUE TITLE
Link to the blog

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/ubports.com#8]
There should be a prominent link to https://blog.ubports.com/ on the landing page. Currently, it's really hard to tell if the project is still alive, because there's no new information anywhere but the blog and the blog is a well kept secret.

Keep up the good work btw, this came out more critical than it was meant. I just think the PR on UBports needs to be a little ...more.

**Comment by NeoTheThird** [comment]
See Pull Request #9

**Comment by UniversalSuperBox** [comment]
I merged the pull request, but it turns out there are two _separate_ navigation bars for differently sized screens. https://github.com/ubports/ubports.com/commit/ca2fbdcb5541e99928cc4926519c2e852f1874d7 fixes this issue completely.

**Comment by NeoTheThird** [comment]
Thx. Sorry, i was not aware of that.
